-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/comitem.xls

local comitem = {
	[20101000]={name="体力药",desc="补体",artid=1003,Level=1,MoneyType=0,BasePrice=10,LayedNum=99,value=10},
	[20102000]={name="加元宝",desc="增加元宝",artid=1002,Level=1,MoneyType=0,BasePrice=12,LayedNum=99,value=12},
	[20103000]={name="经验药",desc="增加英雄经验",artid=1004,Level=1,MoneyType=0,BasePrice=11,LayedNum=99,value=11},
	[20104000]={name="宝箱",desc="打开得到物品",artid=1006,Level=1,MoneyType=0,BasePrice=12,LayedNum=99},
	[20105000]={name="加金币",desc="加金币",artid=1001,Level=1,MoneyType=0,BasePrice=12,LayedNum=99,value=20},
}
return comitem

