-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local armArt = {
	[1]={
		{file="bubing-wait.png",epf="d-"},
		{file="bubing-dead.png"},
		{file="bubing-move%d.png"},
		{file="bubing-atk%d.png"},
		{file="bubing-underatk.png"},
	},
	[2]={
		{file="qibing-wait.png",epf="d-"},
		{file="qibing-dead.png"},
		{file="qibing-move%d.png"},
		{file="qibing-atk%d.png"},
		{file="qibing-underatk.png"},
	},
	[3]={
		{file="gongbing-wait.png",epf="d-"},
		{file="gongbing-dead.png"},
		{file="gongbing-move%d.png"},
		{file="gongbing-atk%d.png"},
		{file="gongbing-underatk.png"},
	},
	[4]={
		{file="gongchengche-wait.png",epf="d-"},
		{file="gongchengche-dead.png"},
		{file="gongchengche-move%d.png"},
		{file="gongchengche-atk%d.png"},
		{file="gongchengche-underatk.png"},
	},
}
return armArt

