-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local herosSkillRule = {
	[1]={
		{skillTempId=21000,skllLevel=1,skillName="火焰"},
		{skillTempId=31000,skllLevel=1,skillName="大火焰"},
		{skillTempId=96000,skllLevel=1,skillName="被动加速度"},
	},
	[2]={
		{skillTempId=22000,skllLevel=1,skillName="蓝火"},
		{skillTempId=32000,skllLevel=1,skillName="台风"},
	},
	[3]={
		{skillTempId=21000,skllLevel=1,skillName="火焰"},
		{skillTempId=40000,skllLevel=1,skillName="盾牌"},
		{skillTempId=90000,skllLevel=1,skillName="被动加血上限"},
	},
	[4]={
		{skillTempId=22000,skllLevel=1,skillName="蓝火"},
		{skillTempId=32000,skllLevel=1,skillName="台风"},
	},
	[5]={
		{skillTempId=21000,skllLevel=1,skillName="火焰"},
		{skillTempId=31000,skllLevel=1,skillName="大火焰"},
	},
	[6]={
		{skillTempId=22000,skllLevel=1,skillName="蓝火"},
		{skillTempId=31000,skllLevel=1,skillName="大火焰"},
	},
}
return herosSkillRule

