-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local armsSkillRule = {
	[1]={
		{skillTempId=1000,skllLevel=1,skillName="步兵攻击"},
	},
	[2]={
		{skillTempId=4000,skllLevel=1,skillName="骑兵攻击"},
	},
	[3]={
		{skillTempId=3000,skllLevel=1,skillName="弓兵攻击"},
	},
	[4]={
		{skillTempId=5000,skllLevel=1,skillName="工程车攻击"},
	},
}
return armsSkillRule

