-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local heros = {
	[1]={
		{id=1001,nickname="关羽",Desc="关公",Artid=1001,ArmId=2001,SkillRule=-1,Level=1,Quality=1,country=1,stars=1,equip_rule=1001,FormationId=1,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=100,MaxMP=100,PhysicsAtk=20,PhysicsDef=10,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
	[2]={
		{id=2001,nickname="刘备",Desc="刘鼻涕",Artid=2001,ArmId=1002,SkillRule=2,Level=1,Quality=1,country=1,stars=2,equip_rule=2001,FormationId=2,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=150,MaxMP=100,PhysicsAtk=20,PhysicsDef=5,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
	[3]={
		{id=3001,nickname="张飞",Desc="张妃",Artid=3001,ArmId=3002,SkillRule=3,Level=1,Quality=1,country=1,stars=3,equip_rule=3001,FormationId=3,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=100,MaxMP=100,PhysicsAtk=20,PhysicsDef=5,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
	[4]={
		{id=4001,nickname="曹操",Desc="蒋干的好机油",Artid=4001,ArmId=1003,SkillRule=4,Level=1,Quality=1,country=2,stars=4,equip_rule=4001,FormationId=4,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=200,MaxMP=100,PhysicsAtk=30,PhysicsDef=17,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
	[5]={
		{id=5001,nickname="孙策",Desc="江东小霸王",Artid=5001,ArmId=4001,SkillRule=5,Level=1,Quality=1,country=3,stars=5,equip_rule=5001,FormationId=5,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=200,MaxMP=100,PhysicsAtk=30,PhysicsDef=17,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
	[6]={
		{id=6001,nickname="孙权",Desc="江东小霸王之弟",Artid=6001,ArmId=1003,SkillRule=6,Level=1,Quality=1,country=3,stars=1,equip_rule=6001,FormationId=6,Con=1,ConInc=1.0,Captain=1,CaptainInc=1.0,Str=1,StrInc=1.0,Speed=1,SpeedInc=1.0,Int=1,IntInc=1.0,Cha=1,ChaInc=1.0,Hit=70,Evd=0,Crt=10,Crtdef=5,DecDef=3,DecDefRed=3,MaxRage=100,MaxHP=200,MaxMP=100,PhysicsAtk=30,PhysicsDef=17,MagicAtk=20,MagicDef=10,TacticsAtk=15,TacticsDef=10},
	},
}
return heros

