-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/home.xls

local homeBuild = {
	[1]={
		{name="兵营",resId=1001,resTitleId=1002,isOpen=false},
	},
	[2]={
		{name="仓库",resId=2001,resTitleId=2002,isOpen=false},
	},
	[3]={
		{name="策略府",resId=3001,resTitleId=3002,isOpen=true},
	},
	[4]={
		{name="大厅",resId=4001,resTitleId=4002,isOpen=false},
	},
	[5]={
		{name="校场",resId=5001,resTitleId=5002,isOpen=true},
	},
	[6]={
		{name="集市",resId=6001,resTitleId=6002,isOpen=false},
	},
	[7]={
		{name="酒馆",resId=7001,resTitleId=7002,isOpen=false},
	},
	[8]={
		{name="民居",resId=8001,resTitleId=8002,isOpen=false},
	},
	[9]={
		{name="粮仓",resId=9001,resTitleId=9002,isOpen=false},
	},
	[10]={
		{name="农田",resId=10001,resTitleId=10002,isOpen=false},
	},
	[11]={
		{name="铸币厂",resId=11001,resTitleId=11002,isOpen=false},
	},
	[12]={
		{name="铁匠部",resId=12001,resTitleId=12002,isOpen=false},
	},
	[13]={
		{name="作坊",resId=13001,resTitleId=13002,isOpen=false},
	},
}
return homeBuild

