-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip_enhance.xls

local equip_enhance = {
	[1]={money=10,stuff_id=30100000,stuff_num=1,attr_percent1=1000,attr_percent2=900},
	[2]={money=11,stuff_id=30100000,stuff_num=1,attr_percent1=2000},
	[3]={money=12,stuff_id=30100000,stuff_num=1,attr_percent1=3000},
	[4]={money=13,stuff_id=30100000,stuff_num=1,attr_percent1=4000},
	[5]={money=14,stuff_id=30100000,stuff_num=1,attr_percent1=5000},
	[6]={money=15,stuff_id=30100000,stuff_num=1,attr_percent1=5500},
	[7]={money=16,stuff_id=30100000,stuff_num=1,attr_percent1=6000},
	[8]={money=17,stuff_id=30100000,stuff_num=1,attr_percent1=6500},
	[9]={money=18,stuff_id=30100000,stuff_num=1,attr_percent1=7000},
	[10]={money=19,stuff_id=30100000,stuff_num=1,attr_percent1=8000},
	[11]={money=20,stuff_id=30100000,stuff_num=1,attr_percent1=9000},
	[12]={money=21,stuff_id=30100000,stuff_num=1,attr_percent1=10000},
	[13]={money=22,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[14]={money=23,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[15]={money=24,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[16]={money=25,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[17]={money=26,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[18]={money=27,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
	[19]={money=28,stuff_id=30100000,stuff_num=1,attr_percent1=1000},
}
return equip_enhance

