-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/gem.xls

local gem = {
	[50100000]={name="猫眼石(1级)",desc="象猫眼一样的宝石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G希望宝石",artid=1000,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,PhysicsAtk=10},
	[50100001]={name="虎眼石(1级)",desc="象虎眼一样的宝石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G希望宝石",artid=1001,Level=1,MoneyType=0,BasePrice=11,LayedNum=20,PhysicsAtk=10},
	[50100002]={name="黄晶石(1级)",desc="黄色的晶石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G智慧宝石",artid=1002,Level=1,MoneyType=0,BasePrice=12,LayedNum=20,PhysicsDef=10},
	[50100003]={name="蓝晶石(1级)",desc="蓝色的晶石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G智慧宝石",artid=1003,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,MagicAtk=10},
	[50100004]={name="红晶石(1级)",desc="红色的晶石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G智慧宝石",artid=1004,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,MagicDef=10},
	[50100005]={name="绿晶石(1级)",desc="绿色的晶石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G智慧宝石",artid=1005,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,MaxMP=10,TacticsAtk=10},
	[50200000]={name="猫眼石(2级)",desc="象猫眼一样的宝石，可以镶嵌在攻击性装备(武器、护腕、戒指、护符、项链)上，使用后不可再镶嵌同类宝石。#r#G希望宝石",artid=2000,Level=1,MoneyType=0,BasePrice=100,LayedNum=20,PhysicsAtk=100},
}
return gem

