-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/gem.xls

local gem_art = {
	[1000]={icon="gem/s_8001.png"},
	[1001]={icon="gem/s_8002.png"},
	[1002]={icon="gem/s_8003.png"},
	[1003]={icon="gem/s_8004.png"},
	[1004]={icon="gem/s_8005.png"},
	[1005]={icon="gem/s_8006.png"},
	[2000]={icon="gem/s_8007.png"},
}
return gem_art

