-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/comitem.xls

local comitem = {
	[20101000]={name="体力药",desc="补体",artid=1000,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,value=10},
	[20102000]={name="经验药",desc="增加英雄经验",artid=1001,Level=1,MoneyType=0,BasePrice=11,LayedNum=20,value=11},
	[20103000]={name="加元宝",desc="增加元宝",artid=1002,Level=1,MoneyType=0,BasePrice=12,LayedNum=20,value=10},
}
return comitem

