-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/skill.xls

local bigHeadIcon = {
	[1]={
		{id=1001},
	},
}
return bigHeadIcon

