-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/skill.xls
-- created at: Wed Sep 17 07:01:08 2014


local initializeData = {}

initializeData.initData2s = {}
local initData2s = initializeData.initData2s
initData2s[1] = {
	TypeId = 2,
	TypeName = "initData2",
	value = 100,
}

initializeData.initData1s = {}
local initData1s = initializeData.initData1s
initData1s[1] = {
	TypeId = 1,
	TypeName = "initData1",
	value = 80,
}

initializeData.type_map = {}
local type_map = initializeData.type_map
type_map[2] = "initData2s" type_map["initData2s"] = 2
type_map[1] = "initData1s" type_map["initData1s"] = 1

initializeData.all_type= {}
local all_type = initializeData.all_type
all_type[2] = initData2s
all_type[1] = initData1s

for i,v in pairs(initializeData.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return initializeData

