-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/skill.xls

local skillEffects = {
	[1001]={
		{name="scene_effect_shandian%d.png",effMoveType=2,time=1000,hitTime="800",amountFrames=2,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[2001]={
		{name="scene_effect_huoyan%d.png",effMoveType=2,time=1200,hitTime="800",amountFrames=7,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[3001]={
		{name="scene_effect_dahuoyan%d.png",effMoveType=2,time=1100,hitTime="500|1000",amountFrames=11,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[4001]={
		{name="scene_effect_lanhuo%d.png",effMoveType=2,time=1000,hitTime="800",amountFrames=4,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[5001]={
		{name="scene_effect_taifeng%d.png",effMoveType=2,time=1200,hitTime="800",amountFrames=12,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[6001]={
		{name="effect/arrow1.png",effMoveType=4,time=1000,hitTime="1000",amountFrames=1,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[7001]={
		{name="effect/arrow2.png",effMoveType=4,time=1000,hitTime="1000",amountFrames=1,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[8001]={
		{name="effect/shitou.png",effMoveType=4,time=1000,hitTime="1000",amountFrames=1,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[9001]={
		{name="effect/fireball.png",effMoveType=1,time=1000,hitTime="1000",amountFrames=1,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[100001]={
		{name="effect_zhuoshao%d.png",effMoveType=1,time=1000,amountFrames=15,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[1]={
		{name="effect_hit%d.png",effMoveType=2,time=500,amountFrames=3,startOffsetPos="0|0",tarOffsetPos="0|0",scale=50},
	},
	[100002]={
		{name="effect_poison%d.png",effMoveType=1,time=1000,amountFrames=4,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[100003]={
		{name="effect_stun%d.png",effMoveType=1,time=1000,amountFrames=4,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[200001]={
		{name="effect_trap%d.png",effMoveType=2,time=500,amountFrames=3,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
	[100004]={
		{name="effect_shield%d.png",effMoveType=1,time=500,amountFrames=4,startOffsetPos="0|0",tarOffsetPos="0|0",scale=100},
	},
}
return skillEffects

