-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/skill.xls

local skillData = {}

skillData.sd_adddefends = {}
local sd_adddefends = skillData.sd_adddefends
sd_adddefends[1] = {
	TypeId = 40,
	TypeName = "sd_adddefend",
	id = 40001,
	lev = 1,
	appendImpactRule = 40001,
	sikllBrief = "盾牌",
	skillEffId = 1001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 1,
	atkDistance = 0,
	atkRangeType = 0,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_adddefends[2] = {
	id = 40002,
	lev = 2,
	appendImpactRule = 40001,
	sikllBrief = "盾牌",
	skillEffId = 1001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 1,
	atkDistance = 0,
	atkRangeType = 0,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_qibing_atks = {}
local sd_qibing_atks = skillData.sd_qibing_atks
sd_qibing_atks[1] = {
	TypeId = 4,
	TypeName = "sd_qibing_atk",
	id = 4001,
	lev = 1,
	appendImpactRule = 4001,
	sikllBrief = "骑兵攻击",
	skillEffId = 0,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 1,
	atkRangeType = 1,
	aktRangeParam = 4,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_adddefend1s = {}
local sd_adddefend1s = skillData.sd_adddefend1s
sd_adddefend1s[1] = {
	TypeId = 50,
	TypeName = "sd_adddefend1",
	id = 50001,
	lev = 1,
	appendImpactRule = 50001,
	sikllBrief = "金钟罩",
	skillEffId = 1001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 1,
	atkDistance = 0,
	atkRangeType = 0,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_gongbing_atks = {}
local sd_gongbing_atks = skillData.sd_gongbing_atks
sd_gongbing_atks[1] = {
	TypeId = 3,
	TypeName = "sd_gongbing_atk",
	id = 3001,
	lev = 1,
	appendImpactRule = 3001,
	sikllBrief = "弓兵攻击",
	skillEffId = 6001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_zhengxings = {}
local sd_zhengxings = skillData.sd_zhengxings
sd_zhengxings[1] = {
	TypeId = 91,
	TypeName = "sd_zhengxing",
	id = 91001,
	lev = 1,
	appendImpactRule = 91001,
	sikllBrief = "陷阱攻击",
	skillEffId = 1001,
	coolBoutTimes = 1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 1,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_baibuchuanyangs = {}
local sd_baibuchuanyangs = skillData.sd_baibuchuanyangs
sd_baibuchuanyangs[1] = {
	TypeId = 33,
	TypeName = "sd_baibuchuanyang",
	id = 33001,
	lev = 1,
	appendImpactRule = 33001,
	sikllBrief = "百步穿杨",
	skillEffId = 7001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_baibuchuanyangs[2] = {
	id = 33002,
	lev = 2,
	appendImpactRule = 33002,
	sikllBrief = "百步穿杨",
	skillEffId = 7001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_baibuchuanyangs[3] = {
	id = 33003,
	lev = 3,
	appendImpactRule = 33003,
	sikllBrief = "百步穿杨",
	skillEffId = 7001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_baibuchuanyangs[4] = {
	id = 33004,
	lev = 4,
	appendImpactRule = 33004,
	sikllBrief = "百步穿杨",
	skillEffId = 7001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 3,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_dahuoyans = {}
local sd_dahuoyans = skillData.sd_dahuoyans
sd_dahuoyans[1] = {
	TypeId = 31,
	TypeName = "sd_dahuoyan",
	id = 31001,
	lev = 1,
	appendImpactRule = 31001,
	sikllBrief = "大火焰",
	skillEffId = 3001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 1,
	moveParam = 1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_dahuoyans[2] = {
	id = 31002,
	lev = 2,
	appendImpactRule = 31002,
	sikllBrief = "大火焰",
	skillEffId = 3001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 1,
	moveParam = 1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_taifengs = {}
local sd_taifengs = skillData.sd_taifengs
sd_taifengs[1] = {
	TypeId = 32,
	TypeName = "sd_taifeng",
	id = 32001,
	lev = 1,
	appendImpactRule = 32001,
	sikllBrief = "台风",
	skillEffId = 5001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 1,
	moveParam = 1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_taifengs[2] = {
	id = 32002,
	lev = 2,
	appendImpactRule = 32002,
	sikllBrief = "台风",
	skillEffId = 5001,
	coolBoutTimes = 2,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 20,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 1,
	moveParam = 1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_lanhuos = {}
local sd_lanhuos = skillData.sd_lanhuos
sd_lanhuos[1] = {
	TypeId = 22,
	TypeName = "sd_lanhuo",
	id = 22001,
	lev = 1,
	appendImpactRule = 22001,
	sikllBrief = "蓝火",
	skillEffId = 4001,
	coolBoutTimes = 1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 10,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_lanhuos[2] = {
	id = 22002,
	lev = 2,
	appendImpactRule = 22002,
	sikllBrief = "蓝火",
	skillEffId = 4001,
	coolBoutTimes = 1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 10,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_passives = {}
local sd_passives = skillData.sd_passives
sd_passives[1] = {
	TypeId = 90,
	TypeName = "sd_passive",
	id = 90001,
	lev = 1,
	appendImpactRule = 90001,
	sikllBrief = "被动加血上限",
	skillEffId = 1001,
	coolBoutTimes = -1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = -1,
	atkRangeType = -1,
	aktRangeParam = -1,
	isCauseMove = -1,
	moveParam = -1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_passives[2] = {
	id = 90002,
	lev = 2,
	appendImpactRule = 90001,
	sikllBrief = "被动加血上限2",
	skillEffId = 1001,
	coolBoutTimes = -1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = -1,
	atkRangeType = -1,
	aktRangeParam = -1,
	isCauseMove = -1,
	moveParam = -1,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_conkStats = {}
local sd_conkStats = skillData.sd_conkStats
sd_conkStats[1] = {
	TypeId = 41,
	TypeName = "sd_conkStat",
	id = 41001,
	lev = 1,
	appendImpactRule = 41001,
	sikllBrief = "眩晕",
	skillEffId = 1001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 1,
	atkDistance = 0,
	atkRangeType = 0,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_gongchengche_atks = {}
local sd_gongchengche_atks = skillData.sd_gongchengche_atks
sd_gongchengche_atks[1] = {
	TypeId = 5,
	TypeName = "sd_gongchengche_atk",
	id = 5001,
	lev = 1,
	appendImpactRule = 5001,
	sikllBrief = "工程车攻击",
	skillEffId = 8001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 4,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_huoyans = {}
local sd_huoyans = skillData.sd_huoyans
sd_huoyans[1] = {
	TypeId = 21,
	TypeName = "sd_huoyan",
	id = 21001,
	lev = 1,
	appendImpactRule = 21001,
	sikllBrief = "火焰",
	skillEffId = 2001,
	coolBoutTimes = 1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 10,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 4,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}
sd_huoyans[2] = {
	id = 21002,
	lev = 2,
	appendImpactRule = 21002,
	sikllBrief = "火焰",
	skillEffId = 2001,
	coolBoutTimes = 1,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 10,
	isEnterUseSkill = 0,
	atkDistance = 2,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_bubing_atks = {}
local sd_bubing_atks = skillData.sd_bubing_atks
sd_bubing_atks[1] = {
	TypeId = 1,
	TypeName = "sd_bubing_atk",
	id = 1001,
	lev = 1,
	appendImpactRule = 1001,
	sikllBrief = "步兵攻击",
	skillEffId = 0,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 1,
	atkRangeType = 5,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.sd_andAtks = {}
local sd_andAtks = skillData.sd_andAtks
sd_andAtks[1] = {
	TypeId = 61,
	TypeName = "sd_andAtk",
	id = 61001,
	lev = 1,
	appendImpactRule = 61001,
	sikllBrief = "加攻",
	skillEffId = 1001,
	coolBoutTimes = 0,
	needHeroLev = 1,
	consumeActPoint = 0,
	consumeHp = 0,
	consumeMp = 0,
	consumeRage = 0,
	isEnterUseSkill = 0,
	atkDistance = 0,
	atkRangeType = 0,
	aktRangeParam = 1,
	isCauseMove = 0,
	moveParam = 0,
	upLevNeedItemId = 0,
	upLevNeedItemId = 0,
	upLevNeedUseMenoy = 0,
	upLevNeedUseFood = 0,
}

skillData.type_map = {}
local type_map = skillData.type_map
type_map[40] = "sd_adddefends" type_map["sd_adddefends"] = 40
type_map[4] = "sd_qibing_atks" type_map["sd_qibing_atks"] = 4
type_map[50] = "sd_adddefend1s" type_map["sd_adddefend1s"] = 50
type_map[3] = "sd_gongbing_atks" type_map["sd_gongbing_atks"] = 3
type_map[91] = "sd_zhengxings" type_map["sd_zhengxings"] = 91
type_map[33] = "sd_baibuchuanyangs" type_map["sd_baibuchuanyangs"] = 33
type_map[31] = "sd_dahuoyans" type_map["sd_dahuoyans"] = 31
type_map[32] = "sd_taifengs" type_map["sd_taifengs"] = 32
type_map[22] = "sd_lanhuos" type_map["sd_lanhuos"] = 22
type_map[90] = "sd_passives" type_map["sd_passives"] = 90
type_map[41] = "sd_conkStats" type_map["sd_conkStats"] = 41
type_map[5] = "sd_gongchengche_atks" type_map["sd_gongchengche_atks"] = 5
type_map[21] = "sd_huoyans" type_map["sd_huoyans"] = 21
type_map[1] = "sd_bubing_atks" type_map["sd_bubing_atks"] = 1
type_map[61] = "sd_andAtks" type_map["sd_andAtks"] = 61

skillData.all_type= {}
local all_type = skillData.all_type
all_type[40] = sd_adddefends
all_type[4] = sd_qibing_atks
all_type[50] = sd_adddefend1s
all_type[3] = sd_gongbing_atks
all_type[91] = sd_zhengxings
all_type[33] = sd_baibuchuanyangs
all_type[31] = sd_dahuoyans
all_type[32] = sd_taifengs
all_type[22] = sd_lanhuos
all_type[90] = sd_passives
all_type[41] = sd_conkStats
all_type[5] = sd_gongchengche_atks
all_type[21] = sd_huoyans
all_type[1] = sd_bubing_atks
all_type[61] = sd_andAtks

for i,v in pairs(skillData.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return skillData

