-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/skill.xls

local skillTemplate = {
	[1]={
		{id=1000,nickname="步兵攻击",skillDesc="普通攻击",instanceId=1,iconId=100,sound=10001,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=2,isShowAktName=0},
	},
	[2]={
		{id=2000,nickname="百步穿杨",skillDesc="弓箭攻击",instanceId=2,iconId=1033,sound=10002,shakeType=0,type=2,useTarget_type=2,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=1},
	},
	[3]={
		{id=3000,nickname="弓兵攻击",skillDesc="普通攻击",instanceId=3,iconId=1033,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=7000,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[4]={
		{id=4000,nickname="骑兵攻击",skillDesc="普通攻击",instanceId=4,iconId=1035,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=2,isShowAktName=0},
	},
	[5]={
		{id=5000,nickname="工程车攻击2",skillDesc="普通攻击",instanceId=5,iconId=1036,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[21]={
		{id=21000,nickname="火焰",skillDesc="普通攻击",instanceId=21,iconId=1002,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[22]={
		{id=22000,nickname="蓝火",skillDesc="普通攻击",instanceId=22,iconId=1003,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[31]={
		{id=31000,nickname="大火焰",skillDesc="普通攻击",instanceId=31,iconId=1001,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=1,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[32]={
		{id=32000,nickname="台风",skillDesc="普通攻击",instanceId=32,iconId=1019,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[40]={
		{id=40000,nickname="盾牌",skillDesc="普通攻击",instanceId=40,iconId=1029,sound=10003,shakeType=0,type=2,useTarget_type=0,isPlayHeadIcon=0,bigIconId=0,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[41]={
		{id=41000,nickname="眩晕",skillDesc="普通攻击",instanceId=41,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=2,isPlayHeadIcon=0,bigIconId=0,accuracyRate=5000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[61]={
		{id=61000,nickname="加攻",skillDesc="普通攻击",instanceId=61,iconId=1046,sound=10003,shakeType=0,type=2,useTarget_type=0,isPlayHeadIcon=0,bigIconId=0,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=1,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=0},
	},
	[90]={
		{id=90000,nickname="被动加血上限",skillDesc="普通攻击",instanceId=90,iconId=1016,sound=-1,shakeType=-1,type=3,useTarget_type=0,isPlayHeadIcon=-1,bigIconId=-1,accuracyRate=-1,critRate=-1,beLimitControl1=-1,beLimitControl2=-1,isDirectStudy=1,isUseNeedLearn=0,actTime=-1,actHitTime=-1,atkOrGatherTims=-1,isShowAktName=-1},
	},
	[91]={
		{id=91000,nickname="陷阱",skillDesc="陷阱攻击",instanceId=91,iconId=1016,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=0,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=1,actTime=1000,actHitTime=500,atkOrGatherTims=-1,isShowAktName=1},
	},
	[92]={
		{id=92000,nickname="混乱",skillDesc="混乱",instanceId=92,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=1},
	},
	[93]={
		{id=93000,nickname="无法恢复怒气",skillDesc="无法恢复怒气",instanceId=93,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=1,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=0,actTime=1000,actHitTime=500,atkOrGatherTims=1,isShowAktName=1},
	},
	[94]={
		{id=94000,nickname="抵消攻击护盾",skillDesc="抵消攻击护盾",instanceId=94,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=0,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=0,actTime=1000,actHitTime=250,atkOrGatherTims=1,isShowAktName=1},
	},
	[95]={
		{id=95000,nickname="回合前出发效果",skillDesc="回合前出发效果",instanceId=95,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=0,isPlayHeadIcon=0,bigIconId=10001,accuracyRate=10000,critRate=0,beLimitControl1=0,beLimitControl2=0,isDirectStudy=0,isUseNeedLearn=0,actTime=500,actHitTime=500,atkOrGatherTims=1,isShowAktName=1},
	},
	[96]={
		{id=96000,nickname="被动加速度",skillDesc="被动加速度",instanceId=96,iconId=1032,sound=-1,shakeType=-1,type=3,useTarget_type=0,isPlayHeadIcon=-1,bigIconId=-1,accuracyRate=-1,critRate=-1,beLimitControl1=-1,beLimitControl2=-1,isDirectStudy=1,isUseNeedLearn=0,actTime=-1,actHitTime=-1,atkOrGatherTims=-1,isShowAktName=-1},
	},
	[97]={
		{id=97000,nickname="驱散",skillDesc="清理所有效果",instanceId=97,iconId=1032,sound=10003,shakeType=0,type=2,useTarget_type=0,isPlayHeadIcon=0,bigIconId=-1,accuracyRate=10000,critRate=0,beLimitControl1=-1,beLimitControl2=-1,isDirectStudy=1,isUseNeedLearn=0,actTime=-1,actHitTime=-1,atkOrGatherTims=-1,isShowAktName=-1},
	},
}
return skillTemplate

