-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip.xls

local equip = {
	[10101000] = { name="大刀",desc="大刀desc",artid=1000,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=10,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
	[10101001] = { name="泼风刀",desc="泼风刀desc",artid=1001,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=10,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
	[10102000] = { name="铠甲",desc="布衣desc",artid=1002,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=10,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
	[10103000] = { name="书籍",desc="布衣desc",artid=1003,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=10,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
	[10104000] = { name="战马",desc="布衣desc",artid=1004,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=-1,MagicDef=10,TacticsAtk=-1,TacticsDef=-1, },
	[10105000] = { name="披风",desc="布衣desc",artid=1005,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=10,TacticsDef=-1, },
	[10106000] = { name="盾牌",desc="布衣desc",artid=1006,RequireLevel=1,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=10, },
	[10201000] = { name="大刀1",desc="大刀1desc",artid=2000,RequireLevel=10,BasePrice=100,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
	[10202000] = { name="铠甲1",desc="布衣1desc",artid=2001,RequireLevel=10,BasePrice=10,LayedNum=99,Con=-1,Captain=-1,Str=-1,Agi=-1,Int=-1,Cha=-1,Hit=-1,Evd=-1,Crt=-1,CrtDef=-1,Block=-1,AtkSpeed=-1,MaxRage=-1,MaxHP=-1,MaxMP=-1,PhysicsAtk=-1,PhysicsDef=-1,MagicAtk=-1,MagicDef=-1,TacticsAtk=-1,TacticsDef=-1, },
}
return equip

