-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip.xls

local equip = {
	[10101000]={name="大刀",desc="大刀desc",artid=1000,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=16,attr_type2=17,PhysicsAtk=10},
	[10101001]={name="泼风刀",desc="泼风刀desc",artid=1001,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=16,PhysicsAtk=20},
	[10102000]={name="铠甲",desc="布衣desc",artid=1002,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=17,PhysicsDef=10},
	[10103000]={name="书籍",desc="布衣desc",artid=1003,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=18,MagicAtk=10},
	[10104000]={name="战马",desc="布衣desc",artid=1004,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=16,MagicDef=10},
	[10105000]={name="披风",desc="布衣desc",artid=1005,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=17,TacticsAtk=10},
	[10106000]={name="盾牌",desc="布衣desc",artid=1006,Level=1,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=17,TacticsDef=10},
	[10201000]={name="大刀1",desc="大刀1desc",artid=2000,Level=10,BasePrice=100,LayedNum=99,maxlevel=12,attr_type1=16},
	[10202000]={name="铠甲1",desc="布衣1desc",artid=2001,Level=10,BasePrice=10,LayedNum=99,maxlevel=12,attr_type1=17},
}
return equip

