-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip.xls

local equip_output = {
	[10101000] = { stage_id_1=101,stage_id_2=201,stage_id_3=301, },
	[10101001] = { stage_id_1=102,stage_id_2=202,stage_id_3=302, },
	[10102000] = { stage_id_1=103,stage_id_2=203,stage_id_3=303, },
	[10103000] = { stage_id_1=104,stage_id_2=204,stage_id_3=304, },
	[10104000] = { stage_id_1=105,stage_id_2=205,stage_id_3=305, },
	[10105000] = { stage_id_1=106,stage_id_2=206,stage_id_3=306, },
	[10106000] = { stage_id_1=107,stage_id_2=207,stage_id_3=307, },
	[10201000] = { stage_id_1=108,stage_id_2=208,stage_id_3=308, },
	[10202000] = { stage_id_1=109,stage_id_2=209,stage_id_3=309, },
}
return equip_output

