-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/material.xls

local material = {
	[30100000]={name="多彩石",desc="石头",artid=1003,Level=1,MoneyType=0,BasePrice=10,LayedNum=20},
	[30100001]={name="蒲黄",desc="香蒲科植物。味甘平，入肝、心经。有收敛止血，活血祛瘀的功效。可用于制药等。",artid=1004,Level=1,MoneyType=0,BasePrice=10,LayedNum=20},
	[30100002]={name="枇杷",desc="蔷薇科植物。叶可入药，性平，味苦，有清肺下气，和胃降逆，治疗肺热咳嗽，呕吐的功效。可用于制药等。",artid=1005,Level=1,MoneyType=0,BasePrice=10,LayedNum=20},
}
return material

