-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/debris.xls

local debris = {
	[40101000]={name="大刀碎片",desc="拥有10个碎片可合成大刀",artid=1000,Level=1,MoneyType=0,BasePrice=10,LayedNum=99,compound_num=10,compound_result=10101000},
	[40101001]={name="泼风刀碎片",desc="拥有10个碎片可合成泼风刀",artid=1001,Level=1,MoneyType=0,BasePrice=11,LayedNum=99,compound_num=10,compound_result=10101001},
	[40201000]={name="大刀1碎片",desc="拥有20个碎片可合成大刀1",artid=2000,Level=1,MoneyType=0,BasePrice=100,LayedNum=99,compound_num=20,compound_result=10201000},
	[40202000]={name="铠甲1碎片",desc="拥有20个碎片可合成铠甲1",artid=2001,Level=1,MoneyType=0,BasePrice=100,LayedNum=99,compound_num=20,compound_result=10202000},
	[40302001]={name="铠甲1碎片",desc="拥有20个碎片可合成铠甲1",artid=2001,Level=1,MoneyType=0,BasePrice=100,LayedNum=99,compound_num=20,compound_result=10202000},
}
return debris

