-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/item.xls

local item = {
	[20101000] = { name="体力药",desc="补体",artid=1000,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,value=10, },
	[20102000] = { name="经验药",desc="增加英雄经验",artid=1001,Level=1,MoneyType=0,BasePrice=11,LayedNum=20,value=11, },
	[20103000] = { name="加元宝",desc="增加元宝",artid=1002,Level=1,MoneyType=0,BasePrice=12,LayedNum=20,value=10, },
	[30100000] = { name="白英",desc="茄科植物。味苦、辛、微寒，入肝、胆经。有清热，利湿，祛风，解毒，消肿的功效。可用于制药等。",artid=1003,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,value=0, },
	[30100001] = { name="蒲黄",desc="香蒲科植物。味甘平，入肝、心经。有收敛止血，活血祛瘀的功效。可用于制药等。",artid=1004,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,value=0, },
	[30100002] = { name="枇杷",desc="蔷薇科植物。叶可入药，性平，味苦，有清肺下气，和胃降逆，治疗肺热咳嗽，呕吐的功效。可用于制药等。",artid=1005,Level=1,MoneyType=0,BasePrice=10,LayedNum=20,value=0, },
}
return item

