-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip.xls

local equip_art = {
	[1000]={icon="equip/5101.png"},
	[1001]={icon="equip/5202.png"},
	[1002]={icon="equip/5105.png"},
	[1003]={icon="equip/5106.png"},
	[1004]={icon="equip/5107.png"},
	[1005]={icon="equip/5416.png"},
	[1006]={icon="equip/5411.png"},
	[2000]={icon="equip/5341.png"},
	[2001]={icon="equip/5338.png"},
}
return equip_art

