-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/equip.xls

local equip_output = {
	[10101000]={101,201,301,301},
	[10101001]={102,202,302,302},
	[10102000]={103,203,303,303},
	[10103000]={104,204,304,304},
	[10104000]={105,205,305,305},
	[10105000]={106,206,306,306},
	[10106000]={107,207,307,307},
	[10201000]={108,208,308,308},
	[10202000]={109,209,309,309},
}
return equip_output

