-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/heros.xls

local armArt = {
	[1] = {
		{ file="bubing-wait.png",enemyPrefix="d-" },
		{ file="bubing-dead.png" },
		{ file="bubing-move%d.png" },
		{ file="bubing-atk%d.png" },
		{ file="bubing-underatk.png" },
	},
	[2] = {
		{ file="qibing-wait.png",enemyPrefix="d-" },
		{ file="qibing-dead.png" },
		{ file="qibing-move%d.png" },
		{ file="qibing-atk%d.png" },
		{ file="qibing-underatk.png" },
	},
	[3] = {
		{ file="gongbing-wait.png",enemyPrefix="d-" },
		{ file="gongbing-dead.png" },
		{ file="gongbing-move%d.png" },
		{ file="gongbing-atk%d.png" },
		{ file="gongbing-underatk.png" },
	},
	[4] = {
		{ file="gongchengche-wait.png",enemyPrefix="d-" },
		{ file="gongchengche-dead.png" },
		{ file="gongchengche-move%d.png" },
		{ file="gongchengche-atk%d.png" },
		{ file="gongchengche-underatk.png" },
	},
}

local pairs = pairs
for i,v in pairs(armArt) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return armArt

