-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local arms = {
	[1]={
		{id=1001,Level=1,artId=1,Desc="1级步兵",skillRule=1,Speed=120,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
		{id=1002,Level=2,artId=1,Desc="2级步兵",skillRule=1,Speed=120,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
		{id=1003,Level=3,artId=1,Desc="3级步兵",skillRule=1,Speed=120,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
	},
	[2]={
		{id=2001,Level=1,artId=2,Desc="1级骑兵",skillRule=2,Speed=150,MovDis=2,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
		{id=2002,Level=2,artId=2,Desc="2级骑兵",skillRule=2,Speed=150,MovDis=2,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
		{id=2003,Level=3,artId=2,Desc="3级骑兵",skillRule=2,Speed=150,MovDis=2,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
	},
	[3]={
		{id=3001,Level=1,artId=3,Desc="1级弓兵",skillRule=3,Speed=110,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
		{id=3002,Level=2,artId=3,Desc="2级弓兵",skillRule=3,Speed=110,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
	},
	[4]={
		{id=4001,Level=1,artId=4,Desc="1级工程车",skillRule=4,Speed=100,MovDis=1,PhysicsAtkRatio=1,PhysicsDefRatio=1,MagicAtkRatio=1,MagicDefRatio=1,TacticsAtkRatio=1,TacticsDefRatio=1},
	},
}
return arms

