-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/heros.xls

local equip_rule = {
	[4001] = {
		equip_id_1 = 10101000,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
	[5001] = {
		equip_id_1 = 10101001,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
	[6001] = {
		equip_id_1 = 10101001,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
	[1001] = {
		equip_id_1 = 10101000,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
	[2001] = {
		equip_id_1 = 10101001,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
	[3001] = {
		equip_id_1 = 10101000,
		equip_id_2 = 10102000,
		equip_id_3 = 10103000,
		equip_id_4 = 10104000,
		equip_id_5 = 10105000,
		equip_id_6 = 10106000,
	},
}

return equip_rule

