-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/heros.xls

local herosArt = {
	[1]={
		{id=1001,headIcon="actor/hero/s_general1101.png"},
	},
	[2]={
		{id=2001,headIcon="actor/hero/s_general1239.png"},
	},
	[3]={
		{id=3001,headIcon="actor/hero/s_general1302.png"},
	},
	[4]={
		{id=4001,headIcon="actor/hero/s_general1305.png"},
	},
	[5]={
		{id=5001,headIcon="actor/hero/s_general1501.png"},
	},
	[6]={
		{id=6001,headIcon="actor/hero/s_general1226.png"},
	},
}
return herosArt

