-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/heros.xls

local heros = {}

heros.hero_sunces = {}
local hero_sunces = heros.hero_sunces
hero_sunces[1] = {
	TypeId = 5,
	TypeName = "hero_sunce",
	id = 5001,
	nickname = "孙策",
	Desc = "江东小霸王",
	Artid = 5001,
	ArmId = 4001,
	SkillRule = 5,
	Level = 1,
	Quality = 1,
	country = 3,
	equip_rule = 5001,
	FormationId = 5,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 200,
	MaxMP = 100,
	PhysicsAtk = 30,
	PhysicsDef = 17,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.hero_sunquans = {}
local hero_sunquans = heros.hero_sunquans
hero_sunquans[1] = {
	TypeId = 6,
	TypeName = "hero_sunquan",
	id = 6001,
	nickname = "孙权",
	Desc = "江东小霸王之弟",
	Artid = 6001,
	ArmId = 1003,
	SkillRule = 6,
	Level = 1,
	Quality = 1,
	country = 3,
	equip_rule = 6001,
	FormationId = 6,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 200,
	MaxMP = 100,
	PhysicsAtk = 30,
	PhysicsDef = 17,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.hero_liubeis = {}
local hero_liubeis = heros.hero_liubeis
hero_liubeis[1] = {
	TypeId = 2,
	TypeName = "hero_liubei",
	id = 2001,
	nickname = "刘备",
	Desc = "刘鼻涕",
	Artid = 2001,
	ArmId = 1002,
	SkillRule = 2,
	Level = 1,
	Quality = 1,
	country = 1,
	equip_rule = 2001,
	FormationId = 2,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 150,
	MaxMP = 100,
	PhysicsAtk = 20,
	PhysicsDef = 5,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.hero_guanyus = {}
local hero_guanyus = heros.hero_guanyus
hero_guanyus[1] = {
	TypeId = 1,
	TypeName = "hero_guanyu",
	id = 1001,
	nickname = "关羽",
	Desc = "关公",
	Artid = 1001,
	ArmId = 2001,
	SkillRule = -1,
	Level = 1,
	Quality = 1,
	country = 1,
	equip_rule = 1001,
	FormationId = 1,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 100,
	MaxMP = 100,
	PhysicsAtk = 20,
	PhysicsDef = 10,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.hero_caocaos = {}
local hero_caocaos = heros.hero_caocaos
hero_caocaos[1] = {
	TypeId = 4,
	TypeName = "hero_caocao",
	id = 4001,
	nickname = "曹操",
	Desc = "蒋干的好机油",
	Artid = 4001,
	ArmId = 1003,
	SkillRule = 4,
	Level = 1,
	Quality = 1,
	country = 2,
	equip_rule = 4001,
	FormationId = 4,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 200,
	MaxMP = 100,
	PhysicsAtk = 30,
	PhysicsDef = 17,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.hero_zhangfeis = {}
local hero_zhangfeis = heros.hero_zhangfeis
hero_zhangfeis[1] = {
	TypeId = 3,
	TypeName = "hero_zhangfei",
	id = 3001,
	nickname = "张飞",
	Desc = "张妃",
	Artid = 3001,
	ArmId = 3002,
	SkillRule = 3,
	Level = 1,
	Quality = 1,
	country = 1,
	equip_rule = 3001,
	FormationId = 3,
	Con = 1,
	ConInc = 1.0,
	Captain = 1,
	CaptainInc = 1.0,
	Str = 1,
	StrInc = 1.0,
	AtkSpeed = 1,
	AtkSpeedInc = 1.0,
	Int = 1,
	IntInc = 1.0,
	Cha = 1,
	ChaInc = 1.0,
	Hit = 70,
	Evd = 0,
	Crt = 10,
	Crtdef = 5,
	Block = 1,
	MaxRage = 100,
	MaxHP = 100,
	MaxMP = 100,
	PhysicsAtk = 20,
	PhysicsDef = 5,
	MagicAtk = 20,
	MagicDef = 10,
	TacticsAtk = 15,
	TacticsDef = 10,
}

heros.type_map = {}
local type_map = heros.type_map
type_map[5] = "hero_sunces" type_map["hero_sunces"] = 5
type_map[6] = "hero_sunquans" type_map["hero_sunquans"] = 6
type_map[2] = "hero_liubeis" type_map["hero_liubeis"] = 2
type_map[1] = "hero_guanyus" type_map["hero_guanyus"] = 1
type_map[4] = "hero_caocaos" type_map["hero_caocaos"] = 4
type_map[3] = "hero_zhangfeis" type_map["hero_zhangfeis"] = 3

heros.all_type= {}
local all_type = heros.all_type
all_type[5] = hero_sunces
all_type[6] = hero_sunquans
all_type[2] = hero_liubeis
all_type[1] = hero_guanyus
all_type[4] = hero_caocaos
all_type[3] = hero_zhangfeis

for i,v in pairs(heros.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return heros

