-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/skill.xls

local initializeData = {
	[1]={
		{value=80},
	},
	[2]={
		{value=100},
	},
	[3]={
		{value=5},
	},
	[4]={
		{value=5},
	},
}
return initializeData

