-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/skill.xls

local specialObjData = {
	[101]={
		{logicId=1,resEffectId=200001,keepBoutNum=5,affectRangeType=1,targetType=1,affectNum=2,param1=500003,param2=10000},
	},
}
return specialObjData

