-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local depletes = {
	[101]={vigour=10,Money=0},
	[102]={vigour=11,Money=0},
	[103]={vigour=12,Money=0},
	[104]={vigour=13,Money=0},
	[105]={vigour=14,Money=0},
	[106]={vigour=15,Money=0},
	[107]={vigour=16,Money=0},
	[108]={vigour=17,Money=0},
	[109]={vigour=18,Money=0},
	[110]={vigour=19,Money=0},
	[111]={vigour=20,Money=0},
	[112]={vigour=21,Money=0},
	[113]={vigour=22,Money=0},
	[114]={vigour=23,Money=0},
	[115]={vigour=24,Money=0},
	[116]={vigour=25,Money=0},
	[117]={vigour=26,Money=0},
	[118]={vigour=27,Money=0},
	[119]={vigour=28,Money=0},
}
return depletes

