-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/home.xls
-- created at: Tue Sep 23 09:21:01 2014


local homeBuild = {}

homeBuild.homeBuild7s = {}
local homeBuild7s = homeBuild.homeBuild7s
homeBuild7s[1] = {
	TypeId = 7,
	TypeName = "homeBuild7",
	name = "酒馆",
	resId = 7001,
	resTitleId = 7002,
}

homeBuild.homeBuild6s = {}
local homeBuild6s = homeBuild.homeBuild6s
homeBuild6s[1] = {
	TypeId = 6,
	TypeName = "homeBuild6",
	name = "集市",
	resId = 6001,
	resTitleId = 6002,
}

homeBuild.homeBuild5s = {}
local homeBuild5s = homeBuild.homeBuild5s
homeBuild5s[1] = {
	TypeId = 5,
	TypeName = "homeBuild5",
	name = "校场",
	resId = 5001,
	resTitleId = 5002,
}

homeBuild.homeBuild4s = {}
local homeBuild4s = homeBuild.homeBuild4s
homeBuild4s[1] = {
	TypeId = 4,
	TypeName = "homeBuild4",
	name = "大厅",
	resId = 4001,
	resTitleId = 4002,
}

homeBuild.homeBuild3s = {}
local homeBuild3s = homeBuild.homeBuild3s
homeBuild3s[1] = {
	TypeId = 3,
	TypeName = "homeBuild3",
	name = "策略府",
	resId = 3001,
	resTitleId = 3002,
}

homeBuild.homeBuild2s = {}
local homeBuild2s = homeBuild.homeBuild2s
homeBuild2s[1] = {
	TypeId = 2,
	TypeName = "homeBuild2",
	name = "仓库",
	resId = 2001,
	resTitleId = 2002,
}

homeBuild.homeBuild1s = {}
local homeBuild1s = homeBuild.homeBuild1s
homeBuild1s[1] = {
	TypeId = 1,
	TypeName = "homeBuild1",
	name = "兵营",
	resId = 1001,
	resTitleId = 1002,
}

homeBuild.homeBuild9s = {}
local homeBuild9s = homeBuild.homeBuild9s
homeBuild9s[1] = {
	TypeId = 9,
	TypeName = "homeBuild9",
	name = "粮仓",
	resId = 9001,
	resTitleId = 9002,
}

homeBuild.homeBuild8s = {}
local homeBuild8s = homeBuild.homeBuild8s
homeBuild8s[1] = {
	TypeId = 8,
	TypeName = "homeBuild8",
	name = "民居",
	resId = 8001,
	resTitleId = 8002,
}

homeBuild.homeBuild13s = {}
local homeBuild13s = homeBuild.homeBuild13s
homeBuild13s[1] = {
	TypeId = 13,
	TypeName = "homeBuild13",
	name = "作坊",
	resId = 13001,
	resTitleId = 13002,
}

homeBuild.homeBuild12s = {}
local homeBuild12s = homeBuild.homeBuild12s
homeBuild12s[1] = {
	TypeId = 12,
	TypeName = "homeBuild12",
	name = "铁匠部",
	resId = 12001,
	resTitleId = 12002,
}

homeBuild.homeBuild11s = {}
local homeBuild11s = homeBuild.homeBuild11s
homeBuild11s[1] = {
	TypeId = 11,
	TypeName = "homeBuild11",
	name = "铸币厂",
	resId = 11001,
	resTitleId = 11002,
}

homeBuild.homeBuild10s = {}
local homeBuild10s = homeBuild.homeBuild10s
homeBuild10s[1] = {
	TypeId = 10,
	TypeName = "homeBuild10",
	name = "农田",
	resId = 10001,
	resTitleId = 10002,
}

homeBuild.type_map = {}
local type_map = homeBuild.type_map
type_map[7] = "homeBuild7s" type_map["homeBuild7s"] = 7
type_map[6] = "homeBuild6s" type_map["homeBuild6s"] = 6
type_map[5] = "homeBuild5s" type_map["homeBuild5s"] = 5
type_map[4] = "homeBuild4s" type_map["homeBuild4s"] = 4
type_map[3] = "homeBuild3s" type_map["homeBuild3s"] = 3
type_map[2] = "homeBuild2s" type_map["homeBuild2s"] = 2
type_map[1] = "homeBuild1s" type_map["homeBuild1s"] = 1
type_map[9] = "homeBuild9s" type_map["homeBuild9s"] = 9
type_map[8] = "homeBuild8s" type_map["homeBuild8s"] = 8
type_map[13] = "homeBuild13s" type_map["homeBuild13s"] = 13
type_map[12] = "homeBuild12s" type_map["homeBuild12s"] = 12
type_map[11] = "homeBuild11s" type_map["homeBuild11s"] = 11
type_map[10] = "homeBuild10s" type_map["homeBuild10s"] = 10

homeBuild.all_type= {}
local all_type = homeBuild.all_type
all_type[7] = homeBuild7s
all_type[6] = homeBuild6s
all_type[5] = homeBuild5s
all_type[4] = homeBuild4s
all_type[3] = homeBuild3s
all_type[2] = homeBuild2s
all_type[1] = homeBuild1s
all_type[9] = homeBuild9s
all_type[8] = homeBuild8s
all_type[13] = homeBuild13s
all_type[12] = homeBuild12s
all_type[11] = homeBuild11s
all_type[10] = homeBuild10s

for i,v in pairs(homeBuild.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return homeBuild

