-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code(trunk)/tools/xls2lua/xls_flies/home.xls
-- created at: Tue Sep 23 09:21:01 2014


local homeRes = {}

homeRes.homeRes10s = {}
local homeRes10s = homeRes.homeRes10s
homeRes10s[1] = {
	TypeId = 10,
	TypeName = "homeRes10",
	homeResId = 10001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1765,348,-1,-1",
	normal = "scene/home/home_build_nongTian.png",
}
homeRes10s[2] = {
	homeResId = 10002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes10s[3] = {
	homeResId = 10003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes12s = {}
local homeRes12s = homeRes.homeRes12s
homeRes12s[1] = {
	TypeId = 12,
	TypeName = "homeRes12",
	homeResId = 12001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "2138,373,-1,-1",
	normal = "scene/home/home_build_tieJiangBu.png",
	selected = "scene/home/home_build_tieJiangBu_l.png",
}
homeRes12s[2] = {
	homeResId = 12002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes12s[3] = {
	homeResId = 12003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes13s = {}
local homeRes13s = homeRes.homeRes13s
homeRes13s[1] = {
	TypeId = 13,
	TypeName = "homeRes13",
	homeResId = 13001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "405,352,-1,-1",
	normal = "scene/home/home_build_zuoFang.png",
}
homeRes13s[2] = {
	homeResId = 13002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes13s[3] = {
	homeResId = 13003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes11s = {}
local homeRes11s = homeRes.homeRes11s
homeRes11s[1] = {
	TypeId = 11,
	TypeName = "homeRes11",
	homeResId = 11001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1781,113,-1,-1",
	normal = "scene/home/home_build_shouBiChang.png",
}
homeRes11s[2] = {
	homeResId = 11002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes11s[3] = {
	homeResId = 11003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes9s = {}
local homeRes9s = homeRes.homeRes9s
homeRes9s[1] = {
	TypeId = 9,
	TypeName = "homeRes9",
	homeResId = 9001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1628,170,-1,-1",
	normal = "scene/home/home_build_liangCang.png",
}
homeRes9s[2] = {
	homeResId = 9002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes9s[3] = {
	homeResId = 9003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes8s = {}
local homeRes8s = homeRes.homeRes8s
homeRes8s[1] = {
	TypeId = 8,
	TypeName = "homeRes8",
	homeResId = 8001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1486,185,-1,-1",
	normal = "scene/home/home_build_juMin.png",
	selected = "scene/home/home_build_juMin_l.png",
}
homeRes8s[2] = {
	homeResId = 8002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes8s[3] = {
	homeResId = 8003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes7s = {}
local homeRes7s = homeRes.homeRes7s
homeRes7s[1] = {
	TypeId = 7,
	TypeName = "homeRes7",
	homeResId = 7001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1317,205,-1,-1",
	normal = "scene/home/home_build_jiuGuan.png",
	selected = "scene/home/home_build_jiuGuan_l.png",
}
homeRes7s[2] = {
	homeResId = 7002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes7s[3] = {
	homeResId = 7003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes6s = {}
local homeRes6s = homeRes.homeRes6s
homeRes6s[1] = {
	TypeId = 6,
	TypeName = "homeRes6",
	homeResId = 6001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1108,225,-1,-1",
	normal = "scene/home/home_build_jiShi.png",
}
homeRes6s[2] = {
	homeResId = 6002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes6s[3] = {
	homeResId = 6003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes5s = {}
local homeRes5s = homeRes.homeRes5s
homeRes5s[1] = {
	TypeId = 5,
	TypeName = "homeRes5",
	homeResId = 5001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "817,220,-1,-1",
	normal = "scene/home/home_build_jiaoChang.png",
}
homeRes5s[2] = {
	homeResId = 5002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes5s[3] = {
	homeResId = 5003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes4s = {}
local homeRes4s = homeRes.homeRes4s
homeRes4s[1] = {
	TypeId = 4,
	TypeName = "homeRes4",
	homeResId = 4001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "185,241,-1,-1",
	normal = "scene/home/home_build_daTing.png",
}
homeRes4s[2] = {
	homeResId = 4002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes4s[3] = {
	homeResId = 4003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes3s = {}
local homeRes3s = homeRes.homeRes3s
homeRes3s[1] = {
	TypeId = 3,
	TypeName = "homeRes3",
	homeResId = 3001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "2088,107,-1,-1",
	normal = "scene/home/home_build_ceLveFu.png",
}
homeRes3s[2] = {
	homeResId = 3002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes3s[3] = {
	homeResId = 3003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes2s = {}
local homeRes2s = homeRes.homeRes2s
homeRes2s[1] = {
	TypeId = 2,
	TypeName = "homeRes2",
	homeResId = 2001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "874,347,-1,-1",
	normal = "scene/home/home_build_cangKu.png",
	selected = "scene/home/home_build_cangKu_l.png",
}
homeRes2s[2] = {
	homeResId = 2002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes2s[3] = {
	homeResId = 2003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes1s = {}
local homeRes1s = homeRes.homeRes1s
homeRes1s[1] = {
	TypeId = 1,
	TypeName = "homeRes1",
	homeResId = 1001,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "100,100,-1,-1",
	normal = "scene/home/home_build_bingYing.png",
}
homeRes1s[2] = {
	homeResId = 1002,
	resType = 2,
	loadWay = 1,
	ZOrder = 0,
	rect = "0,-50,-1,-1",
	normal = "common/buildTitleBg.png",
}
homeRes1s[3] = {
	homeResId = 1003,
	resType = 3,
	ZOrder = 0,
	rect = "82,23.5,-1,-1",
}

homeRes.homeRes14s = {}
local homeRes14s = homeRes.homeRes14s
homeRes14s[1] = {
	TypeId = 14,
	TypeName = "homeRes14",
	homeResId = 14001,
	resType = 1,
	loadWay = 1,
	ZOrder = 1,
	rect = "594.5,307.5,-1,-1",
	normal = "scene/home/home_diban1.png",
}
homeRes14s[2] = {
	homeResId = 14002,
	resType = 1,
	loadWay = 1,
	ZOrder = 1,
	rect = "1783.5,307.5,-1,-1",
	normal = "scene/home/home_diban2.png",
}
homeRes14s[3] = {
	homeResId = 14003,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1188,307.5,-1,-1",
	normal = "scene/home/home_tiankong.png",
}
homeRes14s[4] = {
	homeResId = 14004,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "1848.5,118,-1,-1",
	normal = "scene/home/home_yuanjing.png",
}
homeRes14s[5] = {
	homeResId = 14005,
	resType = 1,
	loadWay = 1,
	ZOrder = 0,
	rect = "2125.5,489.5,-1,-1",
	normal = "scene/home/home_yun.png",
}

homeRes.type_map = {}
local type_map = homeRes.type_map
type_map[10] = "homeRes10s" type_map["homeRes10s"] = 10
type_map[12] = "homeRes12s" type_map["homeRes12s"] = 12
type_map[13] = "homeRes13s" type_map["homeRes13s"] = 13
type_map[11] = "homeRes11s" type_map["homeRes11s"] = 11
type_map[9] = "homeRes9s" type_map["homeRes9s"] = 9
type_map[8] = "homeRes8s" type_map["homeRes8s"] = 8
type_map[7] = "homeRes7s" type_map["homeRes7s"] = 7
type_map[6] = "homeRes6s" type_map["homeRes6s"] = 6
type_map[5] = "homeRes5s" type_map["homeRes5s"] = 5
type_map[4] = "homeRes4s" type_map["homeRes4s"] = 4
type_map[3] = "homeRes3s" type_map["homeRes3s"] = 3
type_map[2] = "homeRes2s" type_map["homeRes2s"] = 2
type_map[1] = "homeRes1s" type_map["homeRes1s"] = 1
type_map[14] = "homeRes14s" type_map["homeRes14s"] = 14

homeRes.all_type= {}
local all_type = homeRes.all_type
all_type[10] = homeRes10s
all_type[12] = homeRes12s
all_type[13] = homeRes13s
all_type[11] = homeRes11s
all_type[9] = homeRes9s
all_type[8] = homeRes8s
all_type[7] = homeRes7s
all_type[6] = homeRes6s
all_type[5] = homeRes5s
all_type[4] = homeRes4s
all_type[3] = homeRes3s
all_type[2] = homeRes2s
all_type[1] = homeRes1s
all_type[14] = homeRes14s

for i,v in pairs(homeRes.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return homeRes

