-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/home.xls

local homeRes = {
	[1] = {
		{ homeResId=1001,resType=1,loadWay=1,ZOrder=0,rect="100,100,-1,-1",normal="scene/home/home_build_bingYing.png", },
		{ homeResId=1002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=1003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[2] = {
		{ homeResId=2001,resType=1,loadWay=1,ZOrder=0,rect="874,347,-1,-1",normal="scene/home/home_build_cangKu.png",selected="scene/home/home_build_cangKu_l.png", },
		{ homeResId=2002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=2003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[3] = {
		{ homeResId=3001,resType=1,loadWay=1,ZOrder=0,rect="2088,107,-1,-1",normal="scene/home/home_build_ceLveFu.png", },
		{ homeResId=3002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=3003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[4] = {
		{ homeResId=4001,resType=1,loadWay=1,ZOrder=0,rect="185,241,-1,-1",normal="scene/home/home_build_daTing.png", },
		{ homeResId=4002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=4003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[5] = {
		{ homeResId=5001,resType=1,loadWay=1,ZOrder=0,rect="817,220,-1,-1",normal="scene/home/home_build_jiaoChang.png", },
		{ homeResId=5002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=5003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[6] = {
		{ homeResId=6001,resType=1,loadWay=1,ZOrder=0,rect="1108,225,-1,-1",normal="scene/home/home_build_jiShi.png", },
		{ homeResId=6002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=6003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[7] = {
		{ homeResId=7001,resType=1,loadWay=1,ZOrder=0,rect="1317,205,-1,-1",normal="scene/home/home_build_jiuGuan.png",selected="scene/home/home_build_jiuGuan_l.png", },
		{ homeResId=7002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=7003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[8] = {
		{ homeResId=8001,resType=1,loadWay=1,ZOrder=0,rect="1486,185,-1,-1",normal="scene/home/home_build_juMin.png",selected="scene/home/home_build_juMin_l.png", },
		{ homeResId=8002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=8003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[9] = {
		{ homeResId=9001,resType=1,loadWay=1,ZOrder=0,rect="1628,170,-1,-1",normal="scene/home/home_build_liangCang.png", },
		{ homeResId=9002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=9003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[10] = {
		{ homeResId=10001,resType=1,loadWay=1,ZOrder=0,rect="1765,348,-1,-1",normal="scene/home/home_build_nongTian.png", },
		{ homeResId=10002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=10003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[11] = {
		{ homeResId=11001,resType=1,loadWay=1,ZOrder=0,rect="1781,113,-1,-1",normal="scene/home/home_build_shouBiChang.png", },
		{ homeResId=11002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=11003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[12] = {
		{ homeResId=12001,resType=1,loadWay=1,ZOrder=0,rect="2138,373,-1,-1",normal="scene/home/home_build_tieJiangBu.png",selected="scene/home/home_build_tieJiangBu_l.png", },
		{ homeResId=12002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=12003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[13] = {
		{ homeResId=13001,resType=1,loadWay=1,ZOrder=0,rect="405,352,-1,-1",normal="scene/home/home_build_zuoFang.png", },
		{ homeResId=13002,resType=2,loadWay=1,ZOrder=0,rect="0,-50,-1,-1",normal="common/buildTitleBg.png", },
		{ homeResId=13003,resType=3,ZOrder=0,rect="82,23.5,-1,-1", },
	},
	[14] = {
		{ homeResId=14001,resType=1,loadWay=1,ZOrder=1,rect="594.5,307.5,-1,-1",normal="scene/home/home_diban1.png", },
		{ homeResId=14002,resType=1,loadWay=1,ZOrder=1,rect="1783.5,307.5,-1,-1",normal="scene/home/home_diban2.png", },
		{ homeResId=14003,resType=1,loadWay=1,ZOrder=0,rect="1188,307.5,-1,-1",normal="scene/home/home_tiankong.png", },
		{ homeResId=14004,resType=1,loadWay=1,ZOrder=0,rect="1848.5,118,-1,-1",normal="scene/home/home_yuanjing.png", },
		{ homeResId=14005,resType=1,loadWay=1,ZOrder=0,rect="2125.5,489.5,-1,-1",normal="scene/home/home_yun.png", },
	},
}

local pairs = pairs
for i,v in pairs(homeRes) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return homeRes

