-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls
-- created at: Fri Aug 15 08:24:24 2014


local chapters = {}

chapters.chapters3s = {}
local chapters3s = chapters.chapters3s
chapters3s[1] = {
	TypeId = 3,
	TypeName = "chapters3",
	MapName = "新野",
	StagesTypeId = 5,
	ChapterResId = 3001,
}

chapters.chapters2s = {}
local chapters2s = chapters.chapters2s
chapters2s[1] = {
	TypeId = 2,
	TypeName = "chapters2",
	MapName = "董卓之乱",
	StagesTypeId = 3,
	ChapterResId = 2001,
}
chapters2s[2] = {
	MapName = "董卓之乱精英",
	StagesTypeId = 4,
	ChapterResId = 2002,
}

chapters.chapters1s = {}
local chapters1s = chapters.chapters1s
chapters1s[1] = {
	TypeId = 1,
	TypeName = "chapters1",
	MapName = "黄金势力",
	StagesTypeId = 1,
	ChapterResId = 1001,
}
chapters1s[2] = {
	MapName = "黄金势力（精英）",
	StagesTypeId = 2,
	ChapterResId = 1002,
}

chapters.type_map = {}
local type_map = chapters.type_map
type_map[3] = "chapters3s" type_map["chapters3s"] = 3
type_map[2] = "chapters2s" type_map["chapters2s"] = 2
type_map[1] = "chapters1s" type_map["chapters1s"] = 1

chapters.all_type= {}
local all_type = chapters.all_type
all_type[3] = chapters3s
all_type[2] = chapters2s
all_type[1] = chapters1s

for i,v in pairs(chapters.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return chapters

