-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local chapterRes = {
	[1]={
		{ChapterResId=1001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_1.jpg",Bg1="UI/UIstages_1/map_bg/map1.png"},
		{ChapterResId=1002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
	[2]={
		{ChapterResId=2001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_2.jpg",Bg1="UI/UIstages_1/map_bg/map2.png"},
		{ChapterResId=2002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
	[3]={
		{ChapterResId=3001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_3.jpg",Bg1="UI/UIstages_1/map_bg/map3.png"},
		{ChapterResId=3002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
	[4]={
		{ChapterResId=4001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_4.jpg",Bg1="UI/UIstages_1/map_bg/map4.png"},
		{ChapterResId=4002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
	[5]={
		{ChapterResId=5001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_5.jpg",Bg1="UI/UIstages_1/map_bg/map5.png"},
		{ChapterResId=5002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
	[6]={
		{ChapterResId=6001,BgBox="UI/UIstages_1/bg/stage-map-frame.png",Bg="UI/UIstages_1/map_bg/stageselect_map_bg_6.jpg",Bg1="UI/UIstages_1/map_bg/map6.png"},
		{ChapterResId=6002,BgBox="UI/UIstages_1/bg/stage-map-guildraid-frame.png"},
	},
}

local pairs = pairs
for i,v in pairs(chapterRes) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return chapterRes

