-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/stages.xls

local chapters = {
	[1]={
		{MapName="黄金势力",StagesTypeId=1},
		{MapName="黄金势力（精英）",StagesTypeId=2},
	},
	[2]={
		{MapName="董卓之乱",StagesTypeId=3},
		{MapName="董卓之乱精英",StagesTypeId=4},
	},
	[3]={
		{MapName="新野",StagesTypeId=5},
	},
}
return chapters

