-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls
-- created at: Fri Aug 15 08:24:24 2014


local depletes = {}

depletes.Depletes1s = {}
local Depletes1s = depletes.Depletes1s
Depletes1s[1] = {
	TypeId = 1,
	TypeName = "Depletes1",
	depleteId = 101,
	JunJing = 10,
	Money = 0,
}
Depletes1s[2] = {
	depleteId = 102,
	JunJing = 11,
	Money = 0,
}
Depletes1s[3] = {
	depleteId = 103,
	JunJing = 12,
	Money = 0,
}
Depletes1s[4] = {
	depleteId = 104,
	JunJing = 13,
	Money = 0,
}
Depletes1s[5] = {
	depleteId = 105,
	JunJing = 14,
	Money = 0,
}
Depletes1s[6] = {
	depleteId = 106,
	JunJing = 15,
	Money = 0,
}
Depletes1s[7] = {
	depleteId = 107,
	JunJing = 16,
	Money = 0,
}
Depletes1s[8] = {
	depleteId = 108,
	JunJing = 17,
	Money = 0,
}
Depletes1s[9] = {
	depleteId = 109,
	JunJing = 18,
	Money = 0,
}
Depletes1s[10] = {
	depleteId = 110,
	JunJing = 19,
	Money = 0,
}
Depletes1s[11] = {
	depleteId = 111,
	JunJing = 20,
	Money = 0,
}
Depletes1s[12] = {
	depleteId = 112,
	JunJing = 21,
	Money = 0,
}
Depletes1s[13] = {
	depleteId = 113,
	JunJing = 22,
	Money = 0,
}
Depletes1s[14] = {
	depleteId = 114,
	JunJing = 23,
	Money = 0,
}
Depletes1s[15] = {
	depleteId = 115,
	JunJing = 24,
	Money = 0,
}
Depletes1s[16] = {
	depleteId = 116,
	JunJing = 25,
	Money = 0,
}
Depletes1s[17] = {
	depleteId = 117,
	JunJing = 26,
	Money = 0,
}
Depletes1s[18] = {
	depleteId = 118,
	JunJing = 27,
	Money = 0,
}
Depletes1s[19] = {
	depleteId = 119,
	JunJing = 28,
	Money = 0,
}

depletes.type_map = {}
local type_map = depletes.type_map
type_map[1] = "Depletes1s" type_map["Depletes1s"] = 1

depletes.all_type= {}
local all_type = depletes.all_type
all_type[1] = Depletes1s

for i,v in pairs(depletes.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return depletes

