-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local depletes = {
	[1] = {
		{ depleteId=101,JunJing=10,Money=0, },
		{ depleteId=102,JunJing=11,Money=0, },
		{ depleteId=103,JunJing=12,Money=0, },
		{ depleteId=104,JunJing=13,Money=0, },
		{ depleteId=105,JunJing=14,Money=0, },
		{ depleteId=106,JunJing=15,Money=0, },
		{ depleteId=107,JunJing=16,Money=0, },
		{ depleteId=108,JunJing=17,Money=0, },
		{ depleteId=109,JunJing=18,Money=0, },
		{ depleteId=110,JunJing=19,Money=0, },
		{ depleteId=111,JunJing=20,Money=0, },
		{ depleteId=112,JunJing=21,Money=0, },
		{ depleteId=113,JunJing=22,Money=0, },
		{ depleteId=114,JunJing=23,Money=0, },
		{ depleteId=115,JunJing=24,Money=0, },
		{ depleteId=116,JunJing=25,Money=0, },
		{ depleteId=117,JunJing=26,Money=0, },
		{ depleteId=118,JunJing=27,Money=0, },
		{ depleteId=119,JunJing=28,Money=0, },
	},
}

local pairs = pairs
for i,v in pairs(depletes) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return depletes

