-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls
-- created at: Fri Aug 15 08:24:24 2014


local mapRes = {}

mapRes.mapRes1s = {}
local mapRes1s = mapRes.mapRes1s
mapRes1s[1] = {
	TypeId = 1,
	TypeName = "mapRes1",
	mapResId = 101,
	Bg = "scene/battle/bg.jpg",
}
mapRes1s[2] = {
	mapResId = 102,
	Bg = "scene/battle/bbg_fall_fortoforc.jpg",
}

mapRes.type_map = {}
local type_map = mapRes.type_map
type_map[1] = "mapRes1s" type_map["mapRes1s"] = 1

mapRes.all_type= {}
local all_type = mapRes.all_type
all_type[1] = mapRes1s

for i,v in pairs(mapRes.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return mapRes

