-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local mapRes = {
	[1] = {
		{ mapResId=101,Bg="scene/battle/bg.jpg", },
		{ mapResId=102,Bg="scene/battle/bbg_fall_fortoforc.jpg", },
	},
}

local pairs = pairs
for i,v in pairs(mapRes) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return mapRes

