-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/stages.xls

local mapRes = {
	[1]={
		{mapResId=101,Bg="scene/battle/bg.jpg"},
		{mapResId=102,Bg="scene/battle/bbg_fall_fortoforc.jpg"},
	},
}
return mapRes

