-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local monsters = {
	[1] = {
		{ Fid=1,isMaster=1,HeorId=1001, },
		{ isMaster=0,HeorId=3001, },
		{ isMaster=0,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[2] = {
		{ Fid=2,isMaster=0,HeorId=1001, },
		{ isMaster=1,HeorId=6001, },
		{ isMaster=0,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[3] = {
		{ Fid=3,isMaster=0,HeorId=1001, },
		{ isMaster=1,HeorId=2001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[4] = {
		{ Fid=4,isMaster=1,HeorId=5001, },
		{ isMaster=0,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[5] = {
		{ Fid=5,isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[6] = {
		{ Fid=6,isMaster=1,HeorId=1001, },
		{ isMaster=0,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[7] = {
		{ Fid=7,isMaster=0,HeorId=6001, },
		{ isMaster=1,HeorId=4001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[8] = {
		{ Fid=8,isMaster=1,HeorId=6001, },
		{ isMaster=0,HeorId=6001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[9] = {
		{ Fid=9,isMaster=1,HeorId=1001, },
		{ isMaster=0,HeorId=1001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
	[10] = {
		{ Fid=10,isMaster=1,HeorId=2001, },
		{ isMaster=0,HeorId=3001, },
		{ isMaster=0,HeorId=5001, },
		{ isMaster=0,HeorId=2001, },
	},
}

local pairs = pairs
for i,v in pairs(monsters) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return monsters

