-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls
-- created at: Fri Aug 15 08:24:24 2014


local monsters = {}

monsters.monsters6s = {}
local monsters6s = monsters.monsters6s
monsters6s[1] = {
	TypeId = 6,
	TypeName = "monsters6",
	Fid = 6,
	isMaster = 1,
	HeorId = 1001,
}
monsters6s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters6s[3] = {
	isMaster = 0,
	HeorId = 4001,
}
monsters6s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters6s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters7s = {}
local monsters7s = monsters.monsters7s
monsters7s[1] = {
	TypeId = 7,
	TypeName = "monsters7",
	Fid = 7,
	isMaster = 0,
	HeorId = 6001,
}
monsters7s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters7s[3] = {
	isMaster = 1,
	HeorId = 4001,
}
monsters7s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters7s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters4s = {}
local monsters4s = monsters.monsters4s
monsters4s[1] = {
	TypeId = 4,
	TypeName = "monsters4",
	Fid = 4,
	isMaster = 1,
	HeorId = 5001,
}
monsters4s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters4s[3] = {
	isMaster = 0,
	HeorId = 4001,
}
monsters4s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters4s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters5s = {}
local monsters5s = monsters.monsters5s
monsters5s[1] = {
	TypeId = 5,
	TypeName = "monsters5",
	Fid = 5,
	isMaster = 0,
	HeorId = 5001,
}
monsters5s[2] = {
	isMaster = 1,
	HeorId = 4001,
}
monsters5s[3] = {
	isMaster = 0,
	HeorId = 4001,
}
monsters5s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters5s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters2s = {}
local monsters2s = monsters.monsters2s
monsters2s[1] = {
	TypeId = 2,
	TypeName = "monsters2",
	Fid = 2,
	isMaster = 0,
	HeorId = 1001,
}
monsters2s[2] = {
	isMaster = 1,
	HeorId = 6001,
}
monsters2s[3] = {
	isMaster = 0,
	HeorId = 4001,
}
monsters2s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters2s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters3s = {}
local monsters3s = monsters.monsters3s
monsters3s[1] = {
	TypeId = 3,
	TypeName = "monsters3",
	Fid = 3,
	isMaster = 0,
	HeorId = 1001,
}
monsters3s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters3s[3] = {
	isMaster = 1,
	HeorId = 2001,
}
monsters3s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters3s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters1s = {}
local monsters1s = monsters.monsters1s
monsters1s[1] = {
	TypeId = 1,
	TypeName = "monsters1",
	Fid = 1,
	isMaster = 1,
	HeorId = 1001,
}
monsters1s[2] = {
	isMaster = 0,
	HeorId = 3001,
}
monsters1s[3] = {
	isMaster = 0,
	HeorId = 4001,
}
monsters1s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters1s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters8s = {}
local monsters8s = monsters.monsters8s
monsters8s[1] = {
	TypeId = 8,
	TypeName = "monsters8",
	Fid = 8,
	isMaster = 1,
	HeorId = 6001,
}
monsters8s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters8s[3] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters8s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters8s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters9s = {}
local monsters9s = monsters.monsters9s
monsters9s[1] = {
	TypeId = 9,
	TypeName = "monsters9",
	Fid = 9,
	isMaster = 1,
	HeorId = 1001,
}
monsters9s[2] = {
	isMaster = 0,
	HeorId = 1001,
}
monsters9s[3] = {
	isMaster = 0,
	HeorId = 1001,
}
monsters9s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters9s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.monsters10s = {}
local monsters10s = monsters.monsters10s
monsters10s[1] = {
	TypeId = 10,
	TypeName = "monsters10",
	Fid = 10,
	isMaster = 1,
	HeorId = 2001,
}
monsters10s[2] = {
	isMaster = 0,
	HeorId = 6001,
}
monsters10s[3] = {
	isMaster = 0,
	HeorId = 3001,
}
monsters10s[4] = {
	isMaster = 0,
	HeorId = 5001,
}
monsters10s[5] = {
	isMaster = 0,
	HeorId = 2001,
}

monsters.type_map = {}
local type_map = monsters.type_map
type_map[6] = "monsters6s" type_map["monsters6s"] = 6
type_map[7] = "monsters7s" type_map["monsters7s"] = 7
type_map[4] = "monsters4s" type_map["monsters4s"] = 4
type_map[5] = "monsters5s" type_map["monsters5s"] = 5
type_map[2] = "monsters2s" type_map["monsters2s"] = 2
type_map[3] = "monsters3s" type_map["monsters3s"] = 3
type_map[1] = "monsters1s" type_map["monsters1s"] = 1
type_map[8] = "monsters8s" type_map["monsters8s"] = 8
type_map[9] = "monsters9s" type_map["monsters9s"] = 9
type_map[10] = "monsters10s" type_map["monsters10s"] = 10

monsters.all_type= {}
local all_type = monsters.all_type
all_type[6] = monsters6s
all_type[7] = monsters7s
all_type[4] = monsters4s
all_type[5] = monsters5s
all_type[2] = monsters2s
all_type[3] = monsters3s
all_type[1] = monsters1s
all_type[8] = monsters8s
all_type[9] = monsters9s
all_type[10] = monsters10s

for i,v in pairs(monsters.all_type) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return monsters

