-- this file is generated by program!
-- don't change it manaully.
-- source file: E:\Code\MG\ProjectX\code\trunk\tools\xls2lua/xls_flies/stages.xls

local stageRes = {
	[1] = {
		{ stageResId=101,scale=50,ZOrder=0,pos="98.50,59.50",normal="UI/UIstages_1/key_stages/stage-1.png",disabled="UI/UIstages_1/key_stages/stage-1-locked.png", },
		{ stageResId=102,scale=50,ZOrder=1,pos="63.00,100.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=103,scale=50,ZOrder=1,pos="56.00,125.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=104,scale=50,ZOrder=0,pos="99.50,162.50",normal="UI/UIstages_1/key_stages/stage-4.png",disabled="UI/UIstages_1/key_stages/stage-4-locked.png", },
		{ stageResId=105,scale=50,ZOrder=1,pos="153.00,170.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=106,scale=50,ZOrder=1,pos="181.00,160.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=107,scale=50,ZOrder=0,pos="184.00,115.00",normal="UI/UIstages_1/key_stages/stage-7.png",disabled="UI/UIstages_1/key_stages/stage-7-locked.png", },
		{ stageResId=108,scale=50,ZOrder=1,pos="224.00,76.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=109,scale=50,ZOrder=1,pos="249.00,54.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=110,scale=50,ZOrder=1,pos="282.00,49.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=111,scale=50,ZOrder=0,pos="344.00,57.50",normal="UI/UIstages_1/key_stages/stage-11.png",disabled="UI/UIstages_1/key_stages/stage-11-locked.png", },
		{ stageResId=112,scale=50,ZOrder=1,pos="394.00,64.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=113,scale=50,ZOrder=1,pos="417.00,83.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=114,scale=50,ZOrder=1,pos="401.00,107.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=115,scale=50,ZOrder=0,pos="385.00,149.00",normal="UI/UIstages_1/key_stages/stage-15.png",disabled="UI/UIstages_1/key_stages/stage-15-locked.png", },
		{ stageResId=116,scale=50,ZOrder=1,pos="348.00,194.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=117,scale=50,ZOrder=1,pos="316.00,175.00",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=118,scale=50,ZOrder=0,pos="267.50,155.50",normal="UI/UIstages_1/key_stages/stage-18.png",disabled="UI/UIstages_1/key_stages/stage-18-locked.png", },
	},
	[2] = {
		{ stageResId=201,scale=50,ZOrder=1,pos="98.50,59.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=202,scale=50,ZOrder=0,pos="63.00,100.50",normal="UI/UIstages_1/key_stages/stage-20.png",disabled="UI/UIstages_1/key_stages/stage-20-locked.png", },
		{ stageResId=203,scale=50,ZOrder=1,pos="56.00,125.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=204,scale=50,ZOrder=1,pos="99.50,162.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=205,scale=50,ZOrder=0,pos="153.00,170.50",normal="UI/UIstages_1/key_stages/stage-27.png",disabled="UI/UIstages_1/key_stages/stage-27-locked.png", },
		{ stageResId=206,scale=50,ZOrder=1,pos="181.00,160.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=207,scale=50,ZOrder=1,pos="184.00,115.00",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=208,scale=50,ZOrder=1,pos="224.00,76.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=209,scale=50,ZOrder=0,pos="249.00,54.50",normal="UI/UIstages_1/key_stages/stage-27.png",disabled="UI/UIstages_1/key_stages/stage-27-locked.png", },
		{ stageResId=210,scale=50,ZOrder=1,pos="282.00,49.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=211,scale=50,ZOrder=1,pos="344.00,57.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=212,scale=50,ZOrder=0,pos="394.00,64.50",normal="UI/UIstages_1/key_stages/stage-30.png",disabled="UI/UIstages_1/key_stages/stage-30-locked.png", },
		{ stageResId=213,scale=50,ZOrder=1,pos="417.00,83.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=214,scale=50,ZOrder=1,pos="401.00,107.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=215,scale=50,ZOrder=0,pos="385.00,149.00",normal="UI/UIstages_1/key_stages/stage-33.png",disabled="UI/UIstages_1/key_stages/stage-33-locked.png", },
		{ stageResId=216,scale=50,ZOrder=1,pos="348.00,194.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=217,scale=50,ZOrder=1,pos="316.00,175.00",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=218,scale=50,ZOrder=0,pos="267.50,155.50",normal="UI/UIstages_1/key_stages/stage-36.png",disabled="UI/UIstages_1/key_stages/stage-36-locked.png", },
	},
	[3] = {
		{ stageResId=301,scale=50,ZOrder=1,pos="98.50,59.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=302,scale=50,ZOrder=0,pos="63.00,100.50",normal="UI/UIstages_1/key_stages/stage-20.png",disabled="UI/UIstages_1/key_stages/stage-20-locked.png", },
		{ stageResId=303,scale=50,ZOrder=1,pos="56.00,125.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=304,scale=50,ZOrder=1,pos="98.50,59.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=305,scale=50,ZOrder=0,pos="63.00,100.50",normal="UI/UIstages_1/key_stages/stage-20.png",disabled="UI/UIstages_1/key_stages/stage-20-locked.png", },
		{ stageResId=306,scale=50,ZOrder=1,pos="56.00,125.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=307,scale=50,ZOrder=1,pos="99.50,162.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=308,scale=50,ZOrder=0,pos="153.00,170.50",normal="UI/UIstages_1/key_stages/stage-27.png",disabled="UI/UIstages_1/key_stages/stage-27-locked.png", },
		{ stageResId=309,scale=50,ZOrder=1,pos="181.00,160.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=310,scale=50,ZOrder=1,pos="184.00,115.00",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=311,scale=50,ZOrder=1,pos="224.00,76.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=312,scale=50,ZOrder=0,pos="249.00,54.50",normal="UI/UIstages_1/key_stages/stage-27.png",disabled="UI/UIstages_1/key_stages/stage-27-locked.png", },
		{ stageResId=313,scale=50,ZOrder=1,pos="282.00,49.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=314,scale=50,ZOrder=1,pos="344.00,57.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=315,scale=50,ZOrder=0,pos="394.00,64.50",normal="UI/UIstages_1/key_stages/stage-30.png",disabled="UI/UIstages_1/key_stages/stage-30-locked.png", },
		{ stageResId=316,scale=50,ZOrder=1,pos="417.00,83.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=317,scale=50,ZOrder=1,pos="401.00,107.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=318,scale=50,ZOrder=0,pos="385.00,149.00",normal="UI/UIstages_1/key_stages/stage-33.png",disabled="UI/UIstages_1/key_stages/stage-33-locked.png", },
		{ stageResId=319,scale=50,ZOrder=1,pos="348.00,194.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=320,scale=50,ZOrder=1,pos="316.00,175.00",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=321,scale=50,ZOrder=0,pos="267.50,155.50",normal="UI/UIstages_1/key_stages/stage-36.png",disabled="UI/UIstages_1/key_stages/stage-36-locked.png", },
		{ stageResId=322,scale=50,ZOrder=1,pos="98.50,59.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
		{ stageResId=323,scale=50,ZOrder=0,pos="63.00,100.50",normal="UI/UIstages_1/key_stages/stage-20.png",disabled="UI/UIstages_1/key_stages/stage-20-locked.png", },
		{ stageResId=324,scale=50,ZOrder=1,pos="56.00,125.50",normal="UI/UIstages_1/stagecircle_current.png",disabled="UI/UIstages_1/stagecircle_elite.png", },
	},
}

local pairs = pairs
for i,v in pairs(stageRes) do
	local item = v
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end

return stageRes

