-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/code_trunk/tools/xls2lua/xls_flies/stages.xls

local monsters = {
	[1]={Fid=1,master_pos=1,heroId1=1001,heroId2=5001,heroId3=6001,heroId4=2001},
	[2]={Fid=2,master_pos=1,heroId1=1001},
	[3]={Fid=3,master_pos=1,heroId1=1001},
	[4]={Fid=4,master_pos=1,heroId1=5001},
	[5]={Fid=5,master_pos=1,heroId1=5001},
	[6]={Fid=6,master_pos=1,heroId1=1001},
	[7]={Fid=7,master_pos=1,heroId1=6001},
	[8]={Fid=8,master_pos=1,heroId1=6001},
	[9]={Fid=9,master_pos=1,heroId1=1001},
	[10]={Fid=10,master_pos=1,heroId1=2001},
}
return monsters

