-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/material.xls

local material_art = {
	[1000]={icon="item/s_16002.png"},
	[1001]={icon="item/s_16022.png"},
	[1002]={icon="item/silver.png"},
	[1003]={icon="gem/s_8001.png"},
	[1004]={icon="item/s_16018.png"},
	[1005]={icon="item/s_16018.png"},
}
return material_art

